

var optimization_variances = [{
	type: 'radio',
	name: 'compilation_level',
	value: 'WHITESPACE_ONLY',
	label: 'White Space only',
	checked: true
},{
	type: 'radio',
	name: 'compilation_level',
	value: 'SIMPLE_OPTIMIZATIONS',
	label: 'Simple'
},{
	type: 'radio',
	name: 'compilation_level',
	value: 'ADVANCED_OPTIMIZATIONS',
	label: 'Advanced'
}];

var formatting_variances = [{
	type: 'checkbox',
	name: 'formatting',
	value: 'pretty_print ',
	label: 'Pretty print'
},{
	type: 'checkbox',
	name: 'formatting',
	value: 'print_input_delimiter ',
	label: 'Print input delimiter'
}];

var warning_levels_variances = [{
	type: 'radio',
	name: 'warning_level',
	value: 'QUIET',
	label: 'Quiet',
	explain: 'Outputs only syntax error messages and warnings generated by the optimization passes included in the compilation_level for the current compiler run.'
},{
	type: 'radio',
	name: 'warning_level',
	value: 'DEFAULT',
	label: 'Default',
	explain: 'In addition to syntax errors and warnings generated by optimization passes, outputs warnings generated by selected code-checking passes.',
	checked: true
},{
	type: 'radio',
	name: 'warning_level',
	value: 'VERBOSE',
	label: 'Verbose',
	explain: 'In addition to syntax errors and warnings generated by optimization passes, outputs warnings generated by all code-checking passes.'
}];


var html_options = [{
	type: 'checkbox',
	name: 'minify_html',
	value: 'mh',
	label: 'Minify Html'
}];

var js_injection_options = [{
	type: 'radio',
	name: 'js_inject_inline',
	value: 'ije',
	label: 'Inject Js external',
	checked: true
},{
	type: 'radio',
	name: 'js_inject_inline',
	value: 'iji',
	label: 'Inject Js inline'
}];


var css_injection_options = [{
	type: 'checkbox',
	name: 'css_inject_inline',
	value: 'ici',
	label: 'Inject Css inline',
}];


var options_data = {
	OptionsCategories: [{
		cat_name: 'Js',
		more: true,
		Options: [{
			title: 'Optimization',
			list: optimization_variances
		},{
			title: 'Formatting',
			list: formatting_variances
		},{
			title: 'Warnings Level',
			list: warning_levels_variances
		}]
	},{
		cat_name: 'Html',
		more: false,
		Options: [{
			title: 'Optimization',
			list: html_options
		},{
			title: 'Js Injection',
			list: js_injection_options
		},{
			title: 'Css Injection',
			list: css_injection_options
		}]
	}]
};

var options_template = 	
						'{{#OptionsCategories}}' +
							'<table>' +
							'<tr>' +
								'<th colspan="2">{{cat_name}}</th>' +
							'</tr>' +
							'{{#Options}}' +
							'<tr>' +
								'<td>{{title}}</td>' +
								'<td>' +
									'{{#list}}' +
									'<input id="{{value}}" name="{{name}}" {{#checked}}checked{{/checked}} value="{{value}}" type="{{type}}" />'+
									'<label title="{{explain}}" for="{{value}}">{{label}}</label>' + 
									'{{/list}}' +
								'</td>' +
							'</tr>' +
							'{{/Options}}' +
							'{{#more}}' +
							'<tr class="ADVANCED_OPTIMIZATIONS" {{^Options[0].list[2].checked}}style="display:none;"{{/Options[0].list[2].checked}}>'+
								'<td>JS Externs</td>'+
								'<td>'+
									'<textarea name="js_externs"></textarea>'+
								'</td>'+
							'</tr>'+
							'<tr class="ADVANCED_OPTIMIZATIONS" {{^Options[0].list[2].checked}}style="display:none;"{{/Options[0].list[2].checked}}>'+
								'<td>Exclude Default Externs</td>'+
								'<td>'+
									'<input name="exclude_default_externs" value="true" type="checkbox"/>'+
								'</td>'+
							'</tr>'+
							'{{/more}}' +
						'</table>'+
						'{{/OptionsCategories}}';
				




